10/offline tests
graasp/graasp-app-file-drop pull request #11
Opened 2020-09-02 10:31 UTC by pyphilia

I came up with this structure for tests.
- Added a flag `test` to enable the api calls (and avoid the `standalone` mode)
- The `uppy` instance is factored out. That way `uppy` can be faked in the test (but is identical to the one used in `Uploader.js`) and can receive programmatically commands (`addFile`)
- `postMessage` to the api/desktop are detected and the callback is faked in the test. This allows for instance appInstanceResources to be generated and saved.

If this draft is accepted, I can refine the tests and create tests for deletion.

2020-09-04 10:12 UTC, juancarlosfarah requested changes
I love it! I think this is a super test and will set the example for this type of interaction. 👏 

Just some minor changes below.

2020-09-04 10:12 UTC, juancarlosfarah commented on src/actions/context.js
> +    const standalone = !devBool && (testBool || !isInFrame());
Can you add a short comment to explain the logic behind this?

2020-09-04 10:12 UTC, juancarlosfarah commented on cypress/integration/StudentView.spec.js
> +const userId = '5b56e70ab253020033364416';
Can we factor out these three things to `fixtures`?

2020-09-04 10:12 UTC, juancarlosfarah commented on cypress/support/commands.js
> +Cypress.Commands.add('offlineVisit', (mode = DEFAULT_MODE) => {
Change to verb: `visitOffline`.

2020-09-04 10:12 UTC, juancarlosfarah commented on cypress/support/commands.js
> +      spaceId: '5b56e70ab253020033364411',
If factored out to `fixtures`, this can also import from there.

2020-09-04 10:12 UTC, juancarlosfarah commented on cypress/integration/StudentView.spec.js
> +import 'cypress-file-upload';
This is a really great test. I like it!

2020-09-04 10:12 UTC, juancarlosfarah commented on src/utils/uppy.js
> +const configUppy = ({
Let's change this to `configureUppy`, as `config` is usually used as an abbreviation for `configuration`, not the verb "to configure".

2020-09-10 07:28 UTC, pyphilia commented
close #11

2020-09-18 10:11 UTC, juancarlosfarah approved these changes

2020-09-18 10:11 UTC, juancarlosfarah commented
🔥

2020-09-18 11:36 UTC, merged